// LLM Provider types and interfaces

/**
 * Supported Large Language Model providers.
 */
export type LLMProvider = 'gemini' | 'openai' | 'anthropic' | 'custom' | 'openrouter' | 'ollama' | 'gateway'

/**
 * Supported Computer-Aided Design backends.
 */
export type CADBackend = 'openscad' | 'build123d'

/**
 * Configuration for an LLM service instance.
 */
export interface LLMConfig {
  /** The AI provider to use */
  readonly provider: LLMProvider
  /** Specific model identifier (e.g. 'gpt-4o', 'claude-3-sonnet') */
  readonly model: string
  /** API key for authentication (BYOK providers) */
  readonly apiKey: string
  /** Whether the AI features are enabled globally */
  readonly enabled: boolean
  /** Optional custom URL for local or proxy models */
  readonly customEndpoint?: string
  /** Creativity setting (0.0 to 1.0) */
  readonly temperature?: number
  /** Maximum number of tokens to generate in the response */
  readonly maxTokens?: number
  /** Gateway provider: base URL (e.g. https://api.scadgpt.com) */
  readonly gatewayBaseUrl?: string
  /** Gateway provider: license key for X-License-Key header */
  readonly gatewayLicenseKey?: string
}

/**
 * A single message in an LLM conversation history.
 */
export interface LLMMessage {
  /** The role of the message author */
  readonly role: 'user' | 'assistant' | 'system'
  /** The text content of the message */
  readonly content: string
  /** Optional base64 image data for multi-modal requests */
  readonly imageDataUrls?: readonly string[]
}

/**
 * Response structure from an LLM non-streaming request.
 */
export interface LLMResponse {
  /** The full text content generated by the model */
  readonly content: string
  /** The specific model that generated the response */
  readonly model: string
  /** Token usage statistics if provided by the vendor */
  readonly usage?: {
    readonly promptTokens: number
    readonly completionTokens: number
    readonly totalTokens: number
  }
}

/**
 * Callback function triggered when a new token or text chunk is received during streaming.
 * 
 * @param chunk - The new text fragment received in this update
 * @param accumulated - The full response text concatenated so far
 * @param done - True if this is the final chunk and the stream is closing
 */
export type StreamCallback = (chunk: string, accumulated: string, done: boolean) => void

/**
 * Controller for managing and terminating active streaming requests.
 */
export interface StreamController {
  /** Immediately aborts the current network request and stops streaming */
  abort: () => void
}

/**
 * Generic interface for an LLM interaction service.
 * Implementations should handle provider-specific API logic and prompt formatting.
 */
export interface LLMService {
  /**
   * Sends a list of messages to the AI and waits for the full response.
   * 
   * @param messages - Complete conversation history
   * @param currentCode - Optional context: current code in the editor
   * @param cadBackend - Optional context: active CAD backend
   * @param apiContext - Optional context: relevant documentation snippets
   * @returns A promise resolving to the LLM's response
   */
  sendMessage(
    messages: LLMMessage[], 
    currentCode?: string, 
    cadBackend?: CADBackend, 
    apiContext?: string
  ): Promise<LLMResponse>
  
  /**
   * Initiates a streaming response from the AI.
   * 
   * @param messages - Complete conversation history
   * @param onChunk - Callback triggered for each received text fragment
   * @param currentCode - Optional context: current code in the editor
   * @param cadBackend - Optional context: active CAD backend
   * @param apiContext - Optional context: relevant documentation snippets
   * @returns A promise resolving to a stream controller for aborting the request
   */
  streamMessage?(
    messages: LLMMessage[],
    onChunk: StreamCallback,
    currentCode?: string,
    cadBackend?: CADBackend,
    apiContext?: string
  ): Promise<StreamController>
  
  /**
   * Indicates if the service implementation supports token streaming.
   * @returns True if streamMessage is implemented and supported by the provider
   */
  supportsStreaming(): boolean
  
  /**
   * Returns a human-friendly name for the LLM provider.
   */
  getProviderName(): string
}
